---
- name: Ensure git is installed
  apt:
    name: git
    state: present

- debug:
    msg: "{{ users_merged | selectattr('dotfiles_repo', 'string') }}"

- debug:
    msg: "{{ users_merged | selectattr('dotfiles_repo', 'string') | map(attribute='dotfiles_repo') }}"

- debug:
    msg: "{{ users_merged | selectattr('dotfiles_repo', 'string') | map(attribute='dotfiles_repo') | list }}"


- name: Get users dotfiles from git repository
  sudo_user: '{{ item.name }}'
  git:
    repo: '{{ item.dotfiles_repo }}'
    dest: '{{ item.dotfiles_dest | default("~/.config/dotfiles") }}'
    update: true
  with_items: users_merged
  when: ((item.name is defined and item.name) and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.createhome is undefined or item.createhome) and
         (item.dotfiles_repo is defined and item.dotfiles_repo))

- name: Link dotfiles
  sudo_user: '{{ item.0.name }}'
  file:
    src: "{{ item.0.dotfiles_dest | default('~/.config/dotfiles') }}/{{ item.1 | basename }}"
    dest: "{{ item.1 }}"
    state: link
  with_subelements:
    - users_merged
    - 'dotfiles_creates'
  when: ((item.0.name is defined and item.0.name) and
    (item.0.state is undefined or (item.0.state is defined and item.0.state != 'absent')) and
    (item.0.createhome is undefined or item.0.createhome) and
    (item.0.dotfiles_creates is defined) and
    (item.0.dotfiles_repo is defined and item.0.dotfiles_repo))

- name: Configure default shell if specified
  user:
    name: '{{ item.name }}'
    shell: '{{ item.shell | default(omit) }}'
  with_items: users_merged
  when: ((item.name is defined and item.name) and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.createhome is undefined or item.createhome) and
         (item.dotfiles_repo is defined and item.dotfiles_repo))