---

- name: Ensure parent directories exist
  file:
    path: "{{ item.1.dest | dirname }}"
    state: directory
  become_user: '{{ item.0.name }}'
  with_subelements:
    - "{{ (users_system + users_admin + users_normal) | selectattr('files', 'defined') | list }}"
    - 'files'

- name: Save files for users
  copy:
    dest: '{{ item.1.dest }}'
    content: '{{ item.1.content }}'
    owner: '{{ item.1.owner | default(omit) }}'
    group: '{{ item.1.group | default(omit) }}'
    mode: '{{ item.1.mode | default(omit) }}'
  become_user: '{{ item.0.name }}'
  with_subelements:
    - "{{ (users_system + users_admin + users_normal) | selectattr('files', 'defined') | list }}"
    - 'files'